openapi: 3.0.3
info:
  title: WARAN - Impuls zur Erstellung einer Flexband API
  version: 0.8.2
  description: >
    Aufbauend auf dem bereits existierenden API-Webdienst zur prozessualen Abwicklung von Steuerungshandlungen (https://edi-energy.github.io/api-electricity/aktuell-gueltig/#/) und den vorgeschlagenen Erweiterungen zur AdHoc API, werden im vorliegenden Abschnitt neue API Dienste vorgeschlagen. Die Flexband-API bietet erweiterte Möglichkeiten Steurungshandlungen über die MSB-Infrastruktur umzusetzen. Basis hierfür ist der EEBUS Anwendungsfall Power Envelope (POEN), welcher auch unter dem Begriff Hüllkurve oder Flexband bekannt ist. In Abgrenzung zur kurativen Ad-hoc Steuerung, bietet die Hüllkurve dabei die Chance eine proaktive Wirkung, sowie eine bessere Verzahnung von Markt- und Netzinteressen zu gewährleisten. In einem Ampelmodell (siehe Hinweise vom FNN zum Netzbetrieb mit Flexibilitäten) kann die Hüllkurve als Netzbetreiber-Instrument für die grüne und gelbe Ampelphase eingeordnet werden. Als übergeordnetes Ziel aus VNB Perspektive steht die effizientere Auslastung der Infrastruktur und die kostengünstige Integration von steuerbaren Anlagen ("Energiewendeanlagen") in die Niederspannungsnetze. Das generische Flexbandkonzept ermöglicht dabei eine Vielzahl von energiewirtschaftlichen Anwendungsmöglichkeiten. Bei unterschielichen Akteuren (bspw. Netzbetreiber und Lieferant), bildet der MSB ein kosolidiertes Profil. Analog zum Ad-hoc Residualprofil, wird hier das sogenannte "POEN-Residualprofil gebildet. Weitere Details zur Verwendung und Einordnung finden sich in den folgenden Veröffentlichungen: 

    - https://www.ppc-ag.de/de/blog/vorausschauen-statt-nachbessern-steuerung-nach-huellkurve/

    - https://www.vde.com/de/fnn/aktuelles/impuls-flexband 


    Ingesamt ergeben sich die folgenden API Dienste die mit der entsprechenden Berechtigung beim MSB bestellt und genutzt werden können:
      -  Flex-01 - "Übermittlung dynamisches Flexband" Vorgabe der verbrauchsseitigen (POEN Szenario 1) oder der einspeiseseitigen Hüllkurve (POEN Szenario 2).  Es können je nach Berechtigung maximale und minimale Leistungslimits für die nächsten 48 Stunden definiert werden. Der MSB bildet auf der Basis ein POEN-Residualprofil (POEN-RP) und sorgt damit für eine konfliktfreie Übertragung des Flexbandes. 

      -  Flex-02 - TBD: "Übermittlung statisches Flexband"  Vorgabe eines zyklischen, sich täglich wiederholenden Flexbandes. Sofern die Steuerungseinrichtung den statischen Anwendungsfall unterstützt, kann das Profil lokal hinterlegt und autonom ausgeführt werden. Andernfalls sorgt der MSB dafür, dass Flex-01 und Flex-02 zu einem gemeinsamen POEN-Residualprofil verarbeitet und regelmäßig übermittelt werden.

      - Flex-03 - "Übermittlung Fallback" - Vorgabe einer Fallbackkurve (POEN Szenario 3). Es können maximale und minimale Leistungslimits für beide Energierichtungen definiert werden. Die Vorgaben haben einen zeitlichen Bezug (0-24h), aber keine Datumsangabe. Die Fallbackwerte werden temporär bei lokalen Kommunikationsstörungen oder Lücken im POEN-Residualprofil aktiviert. Der MSB sorgt für ein konsolidiertes Fallbackprofil, dieses entspricht dem Steuerungsanwendungsfällen 9 gemäß Implementierungshinweis des BSI (SAF9)

      - Flex-04 - "Löschen von Hülllkurven" - Erlaubt die Löschung von zuvor übermittelten Hüllkurven. Die ausgewählten Profile des jeweiligen Absenders werden gelöscht und das POEN-Residualprofil aktualisiert.





 
  
servers:
  - url: https://api.example.com

tags:
  - name: Anweisung Flexband
    description: MSB = API-Anbieter (Server)
  - name: Antwort Flexband
    description: MSB = API-Nutzer (Client)
  - name: Mitteilung Flexband an Berechtigte
    description: MSB = API-Nutzer (Client)
  

paths:

  /to/msb/flexband/command/poen-dynamic-profile/v0:
    post:
      tags: [Anweisung Flexband]
      summary: Flex-01 -> Übermittlung dynamisches Flexband
      description: >
        Vorgabe der verbrauchsseitigen (POEN Szenario 1) oder der einspeiseseitigen Hüllkurve (POEN Szenario 2).  Es können je nach Berechtigung maximale und minimale Leistungslimits für die nächsten 48 Stunden definiert werden. Der MSB bildet auf der Basis ein POEN-Residualprofil (POEN-RP) und sorgt damit für eine konfliktfreie Übertragung des Flexbandes. Die POEN Residualprofile (POEN RP S1 und POEN RP S2) entsprechen dabei den Steuerungsanwendungsfällen 7 und 8 gemäß Implementierungshinweis des BSI (SAF7 / SAF8).


        **Mögliche energiewirtschaftliche Szenarien:**
         - VNB - §14a EnWG „präventiv” (Bis Ende 2028) -> POEN RP S1
         - 	VNB - Redispatch (2.0/3.0) -> POEN RP S2
         - 	VNB - Vorausschauende Steuerung* -> POEN RP S1/S2
         - LF – Direktvermarktung** -> POEN RP S2
         - LF - Vertrags- und Bilanzoptimierung** -> POEN S1/S2
         - LF – Systemdienstleistungen (aFRR / mFRR ** -> POEN S1/S2

        *Vorausschauende, prognosebasierte Steuerung, vgl. FNN Hinweis „Netzbetrieb mit Flexibilitäten“. Umsetzbar bspw. auf vertraglicher Basis (z.B. per FCA - flexibler Netzanschlussvereinbarung (§17 (2b) EnWG))


        **Insbesondere die Option auch Leistung zu aktivieren und gezielt für Einspeisung bzw. Bezug aus dem Netz zu sorgen, kann eine wichtige Option sein, die optimierte Nutzung der Kleinstflexibilitäten über die iMs Infrastruktur zu realisieren. Gesetzlich/Regulatorische Themen stellen einen „Treiber“ für die marktlichen Steuerungsanwendungsfälle dar (u.a. §10b EEG, §34 (2) MsbG und MiSpeL).


      operationId: createFlexband
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
       # - $ref: '#/components/parameters/controlActor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FlexbandRequest'
      responses:
        '202':
          description: accepted
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '415':
          description: Unsupported Media Type
        '422': 
          description: Unprocessable Entity
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout

  /to/msb/flexband/command/poen-static-profile/v0:
    post:
      tags: [Anweisung Flexband]
      summary: Flex-02 -> Übermittlung statisches Flexband
      description: >
        Statisches, täglich wiederkehrendes Hüllkurvenprofil. Vorgabe der verbrauchsseitigen (POEN Szenario 1) oder der einspeiseseitigen Hüllkurve (POEN Szenario 2).  Es können je nach Berechtigung maximale und minimale Leistungslimits für 24 Stunden definiert werden. Der MSB bildet zusammen mit den dynamisch übermittelten Hüllkurven geeignete POEN-Residualprofil (POEN-RP) und sorgt damit für eine konfliktfreie Übertragung des Flexbandes.
        Die POEN Residualprofile (POEN RP S1 und POEN RP S2) entsprechen dabei den Steuerungsanwendungsfällen 7 und 8 gemäß Implementierungshinweis des BSI (SAF7 / SAF8).



        **Mögliche energiewirtschaftliche Szenarien:**
         - VNB - §14a EnWG „präventiv” (Bis Ende 2028) -> POEN RP S1
         - VNB – Backup-Fahrplan für Kommunikationsstörung -> POEN RP S1/S2
         - LF – Backup-Fahrplan für Kommunikationsstörung -> POEN RP S1/S2


         **Hinweis:** Es gilt zu diskuttieren ob diese Art der Flexband Ausprägung notwendig ist. Eine Alternative könnte die Anpassung der technischen UseCase Spezifikation (EEBUS) sein, sodass stattdessen die Fallbackkurven für die fachlichen Szenarien eingesetzt werden können. Aktuell defineren diese lediglich das temporäre Verhalten bei lokalem Kommunikationsausfall und sind somit ungeeignet. Eine Anpassung, sodass diese auch dauerhaft gültig sind wenn keine dynamische Hüllkurve aktiviert ist, könnte ein Lösungsweg darstellen. 


      operationId: createStaticFlexband
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
       # - $ref: '#/components/parameters/controlActor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FlexbandStaticRequest'
      responses:
        '200':
          description: Erfolgreich verarbeitet
  /to/msb/flexband/parameter/fallback/v0:
    post:
      tags: [Anweisung Flexband]
      summary: Flex-03 -> Konfiguration einer Fallback-Küllkurve
      description: >
        Vorgabe einer Fallbackkurve (POEN Szenario 3). Es können maximale Leistungslimits für die jeweilige  Energierichtungen definiert werden. Die Vorgaben haben einen zeitlichen Bezug (0-24h), aber keine Datumsangabe. Die Fallbackwerte werden temporär bei lokalen Kommunikationsstörungen oder Lücken im POEN-Residualprofil aktiviert. Der MSB sorgt für ein konsolidiertes Fallbackprofil, dieses entspricht dem Steuerungsanwendungsfällen 9 gemäß Implementierungshinweis des BSI (SAF9)
      operationId: createFallback
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
       # - $ref: '#/components/parameters/controlActor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FallbackRequest'
      responses:
        '202':
          description: accepted
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '415':
          description: Unsupported Media Type
        '422': 
          description: Unprocessable Entity
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout

  /to/msb/flexband/reset/v0:
    post:
      tags: [Anweisung Flexband]
      summary: Flex-04 -> Löschen bestehender Hüllkurven
      description: >
        Erlaubt die Deaktivierung/Löschung von zuvor übermittelten Hüllkurven. Es werden alle Einträge des Absenders, die nach dem gewünschten Zeitpunkt liegen, im ausgewählten Profil gelöscht.
      operationId: resetFlexband
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
       # - $ref: '#/components/parameters/controlActor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitialStateRequest'
      responses:
        '200':
          description: Erfolgreich zurückgesetzt

  /from/msb/flexband/preliminaryResponse/v0:
    post:
      tags: [Antwort Flexband]
      summary: Flex-05 -> Vorläufige Antwort
      operationId: preliminaryResponse
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
        - $ref: '#/components/parameters/referenceId'
       # - $ref: '#/components/parameters/controlActor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PreliminaryResponse'
      responses:
        '202':
          description: accepted
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '415':
          description: Unsupported Media Type
        '422': 
          description: Unprocessable Entity
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout

  /from/msb/flexband/finalResponse/v0:
    post:
      tags: [Antwort Flexband]
      summary: Flex-06 -> Finale Antwort
      operationId: finalResponse
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
        - $ref: '#/components/parameters/referenceId'
       # - $ref: '#/components/parameters/controlActor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FinalResponse'
      responses:
        '202':
          description: accepted
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '415':
          description: Unsupported Media Type
        '422': 
          description: Unprocessable Entity
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout

  /from/msb/flexband/information/v0:
    post:
      tags: [Mitteilung Flexband an Berechtigte]
      summary: Flex-07 -> Information an Marktpartner
      operationId: informPartners
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
       # - $ref: '#/components/parameters/controlActor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InformationRequest'
      responses:
        '202':
          description: accepted
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '405':
          description: Method not allowed
        '415':
          description: Unsupported Media Type
        '422': 
          description: Unprocessable Entity
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable
        '504':
          description: Gateway Timeout

components:

  parameters:

    transactionId:
      name: transactionId
      in: header
      description: Externe Transaktions-Id zur eindeutigen Identifikation des Aufrufs des sendenden Marktpartners.
      required: true
      schema:
        type: string
        format: uuid
        example: fd85cf16-c24d-41ff-938d-ff45f2273100

    creationDateTime:
      name: creationDateTime
      in: header
      description: Zeitpunkt an dem der Aufruf erstellt wurde
      required: true
      schema:
        type: string
        format: date-time
        example: 2026-07-07T06:58:27.384Z
    referenceId:
          name: referenceId
          in: header
          description: Externe Vorgangsreferenz zur eindeutigen Identifikation des ursprünglichen Befehls (transactionId aus vorlegleagerten Request "Anweisung Flexband").
          required: true
          schema:
            type: string
            format: uuid
            example: de14872e-71e7-407f-916f-da8dbde05178

    initialTransactionId:
      name: initialTransactionId
      in: header
      description: Zur Angabe des Idempotenzschlüssels im Falle eines Retry.
      required: false
      schema:
        type: string
        format: uuid

    controlActor:
      name: marketPartnerId
      in: header
      required: false
      schema:
        type: string
        description: BDEW-ID

  schemas:
    LocationReference:
      type: object
      required:
        - locationId
      properties:
        locationId:
          type: string
          description: Die ID wird durch den BDEW festgelegt. In der vorliegenden Spezifikation wird angenommen, dasss zukünftig ausschließlich über die SR-ID gesteuert wird.
          pattern: '^C[A-Z0-9]{9}[0-9]$'
          example: C1234848431
        subLocationId:
          type: string
          #items:
          #  type: string
          example: "i:98765_u:238bfn2299vfb3"
          description: Ausblick -> Optionale SubLocationId um zukünftig den Steuerbefehl auf einzelne Geräte unterhalb der SR-ID zu beschränken. Im Standard bezieht sich der Befehl auf den Netzanschlusspunkt (adressiert über die SR-ID). Sollen einzelne Geräte (oder Gerätegruppen) speziell Vermarktet und adressiert werden, kann die SubLocationId genutzt werden.  Es könnte bspw. eine spezifische EMS-ID adressiert werden, sodass eine EMS Hierachie abbildbar wäre inkl unterschiedlichewr Zuständikeit (bspw. im MFH).
          

    FlexbandRequest:
      allOf:
          - $ref: '#/components/schemas/LocationReference'  
          - type: object
            required:
              - poenControlStartTime
              - poenControlProfile
              - poenReason
            properties:
              poenContractId:
                type: string
                description: Ausblick -> Optional und gff zielführned, sofern der POEN UseCase überwiegend auf vertraglicher Basiis eingesetzt wird. Die ID könnte zukünftig bis zu HEMS durchgereicht werden und dort zur Validierung und Nachvollziehbarkeit verwendet werden. Es wäre eine Anpassung am technischen UseCase (EEBUS) notwendig  
                example: LF-2026-4711
              poenReason:
                type: string
                enum:
                  - Contract
                  - Test
                example: Contract
              poenControlStartTime:
                type: string
                format: date-time
                example: "2026-01-15T00:00:00Z"
              poenControlProfile:
                type: string
                enum:
                  - Consumption
                  - FeedIn
                example: Consumption

      #        poenRepetitionFlag:
      #          type: boolean
      #          default: false
      #          example: false
              poenControlSlotsMax:
                type: array
                maxItems: 192
                items:
                  $ref: '#/components/schemas/ControlSlot'
                example:
                  - duration: 900
                    activePowerValue: 11000
                  - duration: 900
                    activePowerValue: 9000
                  - duration: 900
                    activePowerValue: 7000
                  - duration: 900
                    activePowerValue: 5000

              poenControlSlotsMin:
                type: array
                maxItems: 192
                items:
                  $ref: '#/components/schemas/ControlSlot'
                example:
                  - duration: 900
                    activePowerValue: 2000
                  - duration: 900
                    activePowerValue: 2000
                  - duration: 900
                    activePowerValue: 3000
                  - duration: 900
                    activePowerValue: 4000

    FlexbandStaticRequest:
      allOf:
          - $ref: '#/components/schemas/LocationReference'       
          - type: object

            required:
              - poenControlStartTime
              - poenControlProfile
              - poenReason
              - ExecutionRange

            properties:
              poenContractId:
                type: string
                description: Ausblick -> Optional und gff zielführned, sofern der POEN UseCase überwiegend auf vertraglicher Basiis eingesetzt wird. Die ID könnte zukünftig bis zu HEMS durchgereicht werden und dort zur Validierung und Nachvollziehbarkeit verwendet werden. Es wäre eine Anpassung am technischen UseCase (EEBUS) notwendig  
                example: LF-2026-4711
              poenReason:
                type: string
                enum:
                  - Contract
                  - Test
                example: Contract
              poenControlProfile:
                type: string
                enum:
                  - Consumption
                  - FeedIn
                example: Consumption
              ExecutionRange:
                allOf:
                  - type: object
                    required:
                      - executionFrom
                      - executionUntil
                    properties:
                      executionFrom:
                        type: string
                        format: date-time
                      executionUntil:
                        type: string
                        format: date-time
              poenControlStartTime:
                type: string
                pattern: '^([01]\d|2[0-3]):[0-5]\d:[0-5]\dZ$'
                example: "00:00:00Z"
              poenControlSlotsMax:
                type: array
                maxItems: 96
                items:
                  $ref: '#/components/schemas/ControlSlot'
                example:
                  - duration: 900
                    activePowerValue: 11000
                  - duration: 900
                    activePowerValue: 9000
                  - duration: 900
                    activePowerValue: 7000
                  - duration: 900
                    activePowerValue: 5000
              poenControlSlotsMin:
                type: array
                maxItems: 96
                items:
                  $ref: '#/components/schemas/ControlSlot'
                example:
                  - duration: 900
                    activePowerValue: 2000
                  - duration: 900
                    activePowerValue: 2000
                  - duration: 900
                    activePowerValue: 3000
                  - duration: 900
                    activePowerValue: 4000

    FallbackRequest:
      allOf:
          - $ref: '#/components/schemas/LocationReference'  
          - type: object
            required:
              - poenConfigProfile
              - poenConfigSlots
            properties:
              poenContractId:
                type: string
                description: Ausblick -> Optional und gff zielführned, sofern der POEN UseCase überwiegend auf vertraglicher Basiis eingesetzt wird. Die ID könnte zukünftig bis zu HEMS durchgereicht werden und dort zur Validierung und Nachvollziehbarkeit verwendet werden. Es wäre eine Anpassung am technischen UseCase (EEBUS) notwendig  
                example: LF-2026-4711

              poenConfigProfile:
                type: string
                enum:
                  - Fallback_FeedIn
                  - Fallback_Consumption
                example: Fallback_Consumption

              poenConfigSlots:
                type: array
                description: Startzeitpunkt für Fallback-Profile ist immer 00:00:00Z
                maxItems: 96
                items:
                  $ref: '#/components/schemas/FallbackSlot'
                example:
                  - duration: 27000
                    activePowerValue: 8000
                  - duration: 1800
                    activePowerValue: 7500
                  - duration: 1800
                    activePowerValue: 7000
                  - duration: 2700
                    activePowerValue: 6500

    InitialStateRequest:
        allOf:
          - $ref: '#/components/schemas/LocationReference'  
          - type: object
            required:
              - poenStopTime
            properties:
              poenStopTime:
                type: string
                format: date-time
              stopProfile:
                type: string
                example: "Flex-01"
                enum:
                  - Flex-01
                  - Flex-02
                  - Flex-03
                  - All
    PreliminaryResponse:
      allOf:
          - $ref: '#/components/schemas/LocationReference'  
          - type: object
            required:
              - preliminaryState
              - preliminaryResponseCode
            properties:
              preliminaryState:
                type: string
                enum: [possible, unable]
                example: "unable"
              preliminaryResponseCode:
                type: string
                enum: [succeeded, communicationFailure, overload, maintanance, missing contract, invalid message, unable]
                description: >
                  succeeded = erfolgreiche Verarbeitung; 
                  communicationFailure = temporäre Störung in der Gerätekommunikation; 
                  localFailure = Gerät(e) Störung - wird durch Außendienst behoben;
                  customerInteractionRequired = Mitwirkung durch den Betreiber notwendig (bspw. SHIP Pairing);
                  overload = Überlastung der Kommunikationsstrecke;
                  missing contract = Keine gültige Berechtigung;
                  invalid message = Nachricht enthält fachliche Fehler;
                  unable = Sonstiger Fehler, siehe weitere Fehlerbeschreibung.
                example: "customerInteractionRequired"
              preliminaryReason:
                type: string
                example: "Fehlendes Pairing zwischen der Steuerungseinrichtung und der steuerbaren Einrichtung des Betreibers. Eine Kundeninteraktion ist notwendig"

    FinalResponse:
      allOf:
          - $ref: '#/components/schemas/LocationReference'  
          - type: object
            required:
              - state
              - responseCode
            properties:
              state:
                type: string
                enum: [possible, unable]
              responseCode:
                type: string
                enum: [succeeded, communicationFailure, overload, maintanance, missing contract, invalid message, unable]
                description: >
                  succeeded = erfolgreiche Verarbeitung; 
                  communicationFailure = temporäre Störung in der Gerätekommunikation; 
                  localFailure = Gerät(e) Störung - wird durch Außendienst behoben;
                  customerInteractionRequired = Mitwirkung durch den Betreiber notwendig (bspw. SHIP Pairing);
                  overload = Überlastung der Kommunikationsstrecke;
                  missing contract = Keine gültige Berechtigung;
                  invalid message = Nachricht enthält fachliche Fehler;
                  unable = Sonstiger Fehler, siehe weitere Fehlerbeschreibung.
              reason:
                type: string
                description: Freitext zur weiteren Fehlerbeschreibung
            
            example:
                locationId: C1234848431
                state: possible
                responseCode: succeeded 
                reason: Flexband bzw. POEN-Residualprofil erfolgreich in der Steuerungseinrichtung aktiviet.
      

    InformationRequest:
      allOf:
          - $ref: '#/components/schemas/LocationReference'  
          - type: object
            required:
              - partnerId
            properties:
              partnerId:
                type: string
                example: 9900496000005
              dynamicFlexband:
                type: array
                items:
                  $ref: '#/components/schemas/FlexbandRequest'
              staticFlexband:
                type: array
                items:
                  $ref: '#/components/schemas/FlexbandStaticRequest'
              fallbackFlexband:
                type: array
                items:
                  $ref: '#/components/schemas/FallbackRequest'
              resetFlexband:
                type: array
                items:
                  $ref: '#/components/schemas/InitialStateRequest'

    ControlSlot:
      type: object
      required:
        - duration
        - activePowerValue
      properties:
        duration:
          type: integer
          description: Dauer in Sekunden
          minimum: 900
          maximum: 86400
        activePowerValue:
          type: integer
          description: Wirkleistung in kW
          minimum: 0

    FallbackSlot:
      type: object
      required:
        - duration
        - activePowerValue
      properties:
        duration:
          type: integer
          description: Dauer in Sekunden
          minimum: 900
          maximum: 86400
        activePowerValue:
          type: integer
          description: Wirkleistung in kW
          minimum: 0
