openapi: 3.0.3

info:
  title: WARAN - Impuls zur Anpassung der Ad-Hoc-Steuerungs-API
  version: 1.0.0
  description: >
    Aufbauend auf dem bereits existierenden API-Webdienst zur prozessualen Abwicklung von Steuerungshandlungen (https://edi-energy.github.io/api-electricity/aktuell-gueltig/#/), werden im vorliegenden Abschnitt Erweiterungen vorgeschlagen, die es den Marktakteuren ermöglichen das volle Potential der Ad-hoc Steuerung zu nutzen. Zur eindeutigen fachlichen Zuordnung der Steuerungsdienste, soll zunächst präzisiert werden, dass die lokale Weitergabe der Ad-hoc Steuerungshandlungen verbrauchsseitig stets über den EEBUS UseCase LPC und einspeiseseitig stets über den EEBUS UseCase LPP erfolgt.* Neben dem kurativen Ad-hoc Eingriff des Netzbetreiber (bspw. nach $14a EnW) ist es vorgesehen die Anwendungsfälle auch im Kontext weiterer netzstabilisierender Maßnahmen zu verwenden. Dazu zählen u.a. Fallbackszenarien, um im Falle von Kommunikationsstörungen oder bei Spannungswiederkehr ein definiertes Verhalten der steuerbaren Anlagen zu gewährleisten. Damit die unterschiedlichen Szenarien konfliktfrei eingesetzt werden können, sind entsprechende Prioritäten bei der Umsetzung zu berücksichtigen. Die Berücksichtigung der Prioritäten und die Weitergabe der Steuerungshandlungen an die Steuerungseinrichtung bzw. an die steuerbare Einrichtung orientiert sich dabei u.a. an dem FNN Hinweis „Steuerungs-Administration“. Insbesondere das Konzept des Residualprofils wird aufgegriffen und als geeignete Möglichkeit identifiziert, die unterschiedlichen Signale im Backend des Messstellenbetreibers zu harmonisieren. Im aktuellen Abschnitt meint das Ad-hoc Residualprofil dabei die jeweiligen LPC und LPP Werte, die als auszuführendes Array an Werten auf die Steuerungseinrichtung übertragen werden. Die Werte können dabei einen zeitlichen Horizont von mehreren Stunden oder Tagen abdecken. Jeder neue Aufruf sorgt für eine Aktualisierung des Residualprofils.


    Ingesamt ergeben sich die folgenden API Dienste die mit der entsprechenden Berechtigung beim MSB bestellt und genutzt werden können:
      - AdHoc-01 "Priorisierte Ad-hoc Steuerungen" wird ins Residualprofil übernommen und überschreibt zyklische bzw. ältere AdHoc Steuerungshandlungen
      - AdHoc-02 "Zyklische AdHoc Steuerung" wird ins Residualprofil übernommen und täglich wiederkehrend ausgeführt. Kann durch neuere AdHoc Anweisungen übersteuert werden. 
      - AdHoc-03 "Softstart" Wird unabhängig vom Residualprofil aktiviert, sobald es einen unerwarteten Neustart der Steuerungseinrictung gibt (Spannungswiederkehr). Wird mit höchster Priorität ausgeführt und übersteuert somit das Ad-hoc Residualprofil.
      - AdHoc-04 "Failsafe-Konfiguration" Konfiguration der Failsafe Werte gemäß EEBUS LPC / LPP Szenario 2
      - AdHoc-05 "Löschen vorhandener Ad-hoc Steuerungen" setzt die Anweisungen des jeweiligen Absenders auf den ursprünglichen Zustand (i.d.R. unbegrenzt bzw. 100%) zurück. Optional kann das entsprechende Profil zum Zurücksetzen angegeben werden.



    *Fokus liegt auf der digitalen Schnittstelle. Insbesondere im Falle von Steuerungsdiensten wird angenommen, dass die „Relaissteuerung“ lediglich als Übergangslösung zu sehen ist. Die fachliche Ausprägung der Prozesse und API-Dienste sollte daher stets mit dem Fokus auf die digitale EEBUS Steuerung erfolgen. Eine Abwärtskompatibilität zum Relais kann in der Regel gewährleistet werden, ist aber nicht Fokus im vorliegenden Dokument. 

servers:
  - url: https://api.example.de

tags:
  - name: Anweisung AdHoc Steuerungshandlung
  - name: Antwort AdHoc Steuerungshandlung
  - name: Mitteilung AdHoc Steuerungshandlung an Berechtigte

paths:

  /steuerungshandlung/adhocPrio:
    post:
      tags: [Anweisung AdHoc Steuerungshandlung]
      summary: AdHoc-01 Priorisierte Ad-hoc-Steuerung
      operationId: postAdHocPrio
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
        - $ref: '#/components/parameters/controlActor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdHocPrioRequest'
      responses:
        '202': {$ref: '#/components/responses/Accepted'}
        '400': {$ref: '#/components/responses/BadRequest'}
        '401': {$ref: '#/components/responses/Unauthorized'}
        '404': {$ref: '#/components/responses/NotFound'}
        '405': {$ref: '#/components/responses/MethodNotAllowed'}
        '500': {$ref: '#/components/responses/InternalError'}

  /steuerungshandlung/adhocZyklisch:
    post:
      tags: [Anweisung AdHoc Steuerungshandlung]
      summary: AdHoc-02 Zyklische AdHoc Steuerung 
      operationId: postAdHocZyklisch
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
        - $ref: '#/components/parameters/controlActor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdHocZyklischRequest'
      responses:
        '202': {$ref: '#/components/responses/Accepted'}
        '400': {$ref: '#/components/responses/BadRequest'}
        '401': {$ref: '#/components/responses/Unauthorized'}
        '404': {$ref: '#/components/responses/NotFound'}
        '405': {$ref: '#/components/responses/MethodNotAllowed'}
        '500': {$ref: '#/components/responses/InternalError'}

  /steuerungshandlung/softstart:
    post:
      tags: [Anweisung AdHoc Steuerungshandlung]
      summary: AdHoc-03 Softstartprofil
      operationId: postSoftstart
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
        - $ref: '#/components/parameters/controlActor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SoftstartRequest'
      responses:
        '202': {$ref: '#/components/responses/Accepted'}
        '400': {$ref: '#/components/responses/BadRequest'}
        '401': {$ref: '#/components/responses/Unauthorized'}
        '404': {$ref: '#/components/responses/NotFound'}
        '405': {$ref: '#/components/responses/MethodNotAllowed'}
        '500': {$ref: '#/components/responses/InternalError'}

  /steuerungshandlung/failsafe:
    post:
      tags: [Anweisung AdHoc Steuerungshandlung]
      summary: AdHoc-04 Failsafe-Konfiguration
      operationId: postFailsafe
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
        - $ref: '#/components/parameters/controlActor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FailsafeRequest'
      responses:
        '202': {$ref: '#/components/responses/Accepted'}
        '400': {$ref: '#/components/responses/BadRequest'}
        '401': {$ref: '#/components/responses/Unauthorized'}
        '404': {$ref: '#/components/responses/NotFound'}
        '405': {$ref: '#/components/responses/MethodNotAllowed'}
        '500': {$ref: '#/components/responses/InternalError'}

  /steuerungshandlung/initialZustand:
    post:
      tags: [Anweisung AdHoc Steuerungshandlung]
      summary: AdHoc-05 Löschen vorhandener Ad-hoc-Steuerungen
      operationId: postInitialZustand
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
        - $ref: '#/components/parameters/controlActor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitialZustandRequest'
      responses:
        '202': {$ref: '#/components/responses/Accepted'}
        '400': {$ref: '#/components/responses/BadRequest'}
        '401': {$ref: '#/components/responses/Unauthorized'}
        '404': {$ref: '#/components/responses/NotFound'}
        '405': {$ref: '#/components/responses/MethodNotAllowed'}
        '500': {$ref: '#/components/responses/InternalError'}

  /antwort/vorlaeufig:
    post:
      tags: [Antwort AdHoc Steuerungshandlung]
      summary: AdHoc-06 Vorläufige Antwort
      operationId: postPreliminaryResponse
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
        - $ref: '#/components/parameters/controlActor'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PreliminaryResponse'
      responses:
        '202': {$ref: '#/components/responses/Accepted'}
        '400': {$ref: '#/components/responses/BadRequest'}
        '401': {$ref: '#/components/responses/Unauthorized'}
        '404': {$ref: '#/components/responses/NotFound'}
        '405': {$ref: '#/components/responses/MethodNotAllowed'}
        '500': {$ref: '#/components/responses/InternalError'}

  /antwort/final:
    post:
      tags: [Antwort AdHoc Steuerungshandlung]
      summary: AdHoc-07 Finale Antwort
      operationId: postFinalResponse
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
        - $ref: '#/components/parameters/controlActor'      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FinalResponse'
      responses:
        '202': {$ref: '#/components/responses/Accepted'}
        '400': {$ref: '#/components/responses/BadRequest'}
        '401': {$ref: '#/components/responses/Unauthorized'}
        '404': {$ref: '#/components/responses/NotFound'}
        '405': {$ref: '#/components/responses/MethodNotAllowed'}
        '500': {$ref: '#/components/responses/InternalError'}

  /information:
    post:
      tags: [Mitteilung AdHoc Steuerungshandlung an Berechtigte]
      summary: AdHoc-08 Information über aktive Ad-hoc-Steuerungen
      operationId: postInformation
      parameters:
        - $ref: '#/components/parameters/transactionId'
        - $ref: '#/components/parameters/creationDateTime'
        - $ref: '#/components/parameters/initialTransactionId'
        - $ref: '#/components/parameters/controlActor'      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InformationRequest'
      responses:
        '202': {$ref: '#/components/responses/Accepted'}
        '400': {$ref: '#/components/responses/BadRequest'}
        '401': {$ref: '#/components/responses/Unauthorized'}
        '404': {$ref: '#/components/responses/NotFound'}
        '405': {$ref: '#/components/responses/MethodNotAllowed'}
        '500': {$ref: '#/components/responses/InternalError'}

components:
  responses:
    Accepted: {description: Die Anfrage wurde technisch erfolgreich verarbeitet}
    BadRequest: {description: Die Anfrage ist ungültig}
    Unauthorized: {description: Die Anfrage ist nicht autorisiert}
    NotFound: {description: Ressource nicht gefunden}
    MethodNotAllowed: {description: Methode nicht erlaubt}
    InternalError: {description: Interner Fehler}
  parameters:

    transactionId:
      name: transactionId
      in: header
      required: true
      schema:
        type: string
        format: uuid
        example: de14872e-71e7-407f-916f-da8dbde05176


    creationDateTime:
      name: creationDateTime
      in: header
      required: true
      schema:
        type: string
        format: date-time
        example: 2026-07-07T06:58:27.384Z

    initialTransactionId:
      name: initialTransactionId
      in: header
      required: false
      schema:
        type: string
        format: uuid

    controlActor:
      name: controlActor
      in: header
      required: true
      schema:
        type: string
        pattern: '^\d{13}$'
        example: 9900496000005

  schemas:

    LocationReference:
      type: object
      required:
        - locationId
      properties:
        locationId:
          type: string
          pattern: '^C[A-Z0-9]{9}[0-9]$'
          example: C1234848431

    AdHocDirection:
      type: string
      enum:
        - FeedIn
        - Consumption

    AdHocReason:
      type: string
      example: Test
      enum:
        - DSO
        - DSO_TSO
        - Contract
        - Test

    PowerInterval:
      type: object
      required:
        - activePowerValue
      properties:
        activePowerValue:
          type: number
          format: double
          minimum: 0
          example: 4.200

    ExecutionPowerInterval:
      allOf:
        - $ref: '#/components/schemas/PowerInterval'
        - type: object
          required:
            - executionTimeFrom
            - executionTimeUntil
          properties:
            executionTimeFrom:
              type: string
              format: date-time
            executionTimeUntil:
              type: string
              format: date-time

    DurationPowerInterval:
      allOf:
        - $ref: '#/components/schemas/PowerInterval'
        - type: object
          required:
            - duration
          properties:
            duration:
              type: integer
              example: 900

    AdHocPrioItem:
      allOf:
        - $ref: '#/components/schemas/LocationReference'
        - type: object
          properties:
            adHocReason:
              $ref: '#/components/schemas/AdHocReason'
            adHocDirection:
              $ref: '#/components/schemas/AdHocDirection'
            adHocMaximumValues:
              type: array
              items:
                $ref: '#/components/schemas/ExecutionPowerInterval'

    AdHocPrioRequest:
      type: array
      items:
        $ref: '#/components/schemas/AdHocPrioItem'

    AdHocZyklischItem:
      allOf:
        - $ref: '#/components/schemas/LocationReference'
        - type: object
          properties:
            adHocReason:
              $ref: '#/components/schemas/AdHocReason'
            adHocDirection:
              $ref: '#/components/schemas/AdHocDirection'
            adHocMaximumValues:
              type: array
              maxItems: 96
              items:
                $ref: '#/components/schemas/DurationPowerInterval'
              example:
              - activePowerValue: 6
                duration: 900
              - activePowerValue: 4.2
                duration: 3600
              - activePowerValue: 5.3
                duration: 3600
              - activePowerValue: 7.2
                duration: 900


    AdHocZyklischRequest:
      type: array
      items:
        $ref: '#/components/schemas/AdHocZyklischItem'

    SoftstartRequest:
      type: array
      items:
        type: object
        properties:
          locationId:
            type: string
          softstartValuesMaxProduction:
            type: array
            items:
              $ref: '#/components/schemas/DurationPowerInterval'
            example:
              - activePowerValue: 0
                duration: 900
              - activePowerValue: 4.2
                duration: 3600
          softstartValuesMaxConsumption:
            type: array
            items:
              $ref: '#/components/schemas/DurationPowerInterval'
            example:
              - activePowerValue: 2
                duration: 900
              - activePowerValue: 4.2
                duration: 3600

    FailsafeRequest:
      type: array
      items:
        type: object
        properties:
          locationId:
            type: string
          failsafeValueProduction:
            $ref: '#/components/schemas/DurationPowerInterval'
          failsafeValueConsumption:
            $ref: '#/components/schemas/DurationPowerInterval'

    InitialZustandRequest:
      type: object
      properties:
        locationIds:
          type: array
          items:
            type: string
        AdHocStopTime:
          type: string
          format: date-time
        StopProfile:
          type: string
          example: "AdHoc-01"
          enum:
            - AdHoc-01
            - AdHoc-02
            - AdHoc-03


    PreliminaryResponse:
      type: object
      example:
         locationId: C1234848431
         adHocState: possible
         adHocReason: Steuerungseinrichtung erreichbar und Fahrplan plausibel geprüft.
      properties:
        locationId:
          type: string
          example: C1234848431
        adHocPreliminaryState:
          type: string
          enum:
            - possible
            - unable
          example: possible
        adHocPreliminaryReason:
          type: string
          example: Steuerungseinrichtung erreichbar und Fahrplan plausibel geprüft.


    FinalResponse:
      type: object
      example:
          locationId: C1234848431
          adHocState: possible
          adHocReason: Fahrplan erfolgreich in der Steuerungseinrichtung aktiviet.

      properties:
        locationId:
          type: string
        adHocState:
          type: string
          enum:
            - possible
            - unable
        adHocReason:
          type: string

    InformationRequest:
      type: object
      properties:
        locationId:
          type: string
        partnerId:
          type: string
        adHocEndDate:
          type: string
          format: date-time
        adHocValuesMaxConsumption:
          type: array
          items:
            $ref: '#/components/schemas/ExecutionPowerInterval'

        adHocValuesMaxFeedIn:
          type: array
          items:
            $ref: '#/components/schemas/ExecutionPowerInterval'
      example:
        locationId: C1234848431
        partnerId: 9901234567890
        adHocValuesMaxConsumption:
          - activePowerValue: 4.2
            executionTimeFrom: '2025-10-15T17:00:00Z'
            executionTimeUntil: '2025-10-15T17:15:00Z'
          - activePowerValue: 3.5
            executionTimeFrom: '2025-10-15T17:15:00Z'
            executionTimeUntil: '2025-10-15T17:30:00Z'
          - activePowerValue: 2.8
            executionTimeFrom: '2025-10-15T17:30:00Z'
            executionTimeUntil: '2025-10-15T17:45:00Z'
          - activePowerValue: 1.0
            executionTimeFrom: '2025-10-15T17:45:00Z'
            executionTimeUntil: '2025-10-15T18:00:00Z'
        adHocValuesMaxFeedIn:
          - activePowerValue: 8.0
            executionTimeFrom: '2025-10-15T17:00:00Z'
            executionTimeUntil: '2025-10-15T17:15:00Z'
          - activePowerValue: 6.0
            executionTimeFrom: '2025-10-15T17:15:00Z'
            executionTimeUntil: '2025-10-15T17:30:00Z'
          - activePowerValue: 4.0
            executionTimeFrom: '2025-10-15T17:30:00Z'
            executionTimeUntil: '2025-10-15T17:45:00Z'
          - activePowerValue: 2.0
            executionTimeFrom: '2025-10-15T17:45:00Z'
            executionTimeUntil: '2025-10-15T18:00:00Z'
